### ISSUE TITLE
Installation of mailer fails

### ISSUE THREAD

**Issue by callahan22** [alerta/docker-alerta#114]
Hi,

It looks like mailer fails to install as it doesn't reside in the "plugins" directory in the project.
The docker-entrypoint.sh script in alerta runs the following:

```
# Install plugins
  IFS=","
  for plugin in ${INSTALL_PLUGINS}
  do
    echo "Installing plugin '${plugin}'"
    /venv/bin/pip install git+https://github.com/alerta/alerta-contrib.git#subdirectory=plugins/$plugin
  done
  touch ${RUN_ONCE}
fi
```
This fails to install mailer (I'm assuming of course that I'm supposed to define it under plugins as there doesn't appear to be anywhere else I can define it in the alertad.conf file and very little direction as to how to integrate it with alerta).

To get around this, I can run:
```
/venv/bin/pip install git+https://github.com/alerta/alerta-contrib.git#subdirectory=integrations/mailer
Building wheels for collected packages: alerta-mailer
  Building wheel for alerta-mailer (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-2e1nah9o/wheels/9a/49/c1/b19cd89b13b7dc6802bbe04dd0edb93d0a23dcc54948c2c916
Successfully built alerta-mailer
Installing collected packages: vine, amqp, kombu, redis, alerta-mailer
Successfully installed alerta-mailer-5.2.0 amqp-2.4.1 kombu-4.3.0 redis-3.1.0 vine-1.2.0
```
from within the container but obviously not ideal. Additional to that is that despite it saying the alerta-mailer-5.2.0 package has been built and dropped into /tmp/pip-ephem-wheel-cache-2e1nah9o/wheels/9a/49/c1/b19cd89b13b7dc6802bbe04dd0edb93d0a23dcc54948c2c916, that directory does not exist. Even if it did, there is no clear instructions on how to make that implement with alerta.

If anyone can point out if I'm missing something, I'd appreciate it.

**Comment by satterly** [comment]
The `mailer` integration isn't a plugin which is why it won't install using the plugin install method.

If using the docker container I suggest you install it by extending the default docker container, or create your own.

There's an example [here](https://github.com/alerta/docker-alerta/blob/master/examples/ldap/Dockerfile#L10) of how to use the Alerta docker image as the base image and then installing an additional package in the virtual environment -- in your case it would be the mailer integration.

Let me know if you need more info.

**Comment by callahan22** [comment]
Hi Nick,

Many thanks for that pointer. Alerta is installed and running but for the last few hours, I've been battling with AUTH_REQUIRED = True
I've exhausted everything I can think of to fix it (which likely means it's something obvious!).
If I set AUTH_REQUIRED = False, I can obviously access the alerta web interface, create an admin account and then log on with that admin account. Then I can create an API for use with Alert Manager.
What I'd like to do is force the AUTH_REQUIRED = True and assign admin accounts in the alertad.conf. I'm not expecting you to troubleshoot it but if you could maybe have a look over what I have and point out anything I may have missed, I'd appreciate it.
This is what I have:

docker-compose.yml (alerta section)
```
postgres-db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: monitoring

  alerta:
    image: alerta/alerta-web
    container_name: alerta
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    volumes:
      - ./alerta/alerta.conf:/app/alerta.conf
      - ./alerta/alertad.conf:/app/alertad.conf

volumes:
  postgresql_data:
```

alertad.conf...
```
DEBUG = True
DATABASE_URL = 'postgres://postgres:postgres@postgres-db:5432/monitoring'
AUTH_REQUIRED = True
AUTH_PROVIDER = 'basic'  # basic (default), github, gitlab, google, keycloak, pingfederate, saml2
ADMIN_USERS = ['user1@here.com','user2@here.com']
ADMIN_PASSWORD = 'Changeme'
SIGNUP_ENABLED = False
```

```
[DEFAULT]
timezone = Europe/London
output = json

[profile Development]
endpoint = http://server1.testnet.com:8080
key = demo-key
sslverify = off
timeout = 10.0
debug = yes

[profile Production]
endpoint = http://server1.testnet.com:8080
key = demo-key
sslverify = off
timeout = 10.0
debug = yes

[alerta-mailer]
key = demo-key
mail_to = me@testnet.com
mail_from = alerta@testnet.com
dashboard_url = http://server1.testnet.com:8080
smtp_username =
smtp_password =
smtp_use_ssl = False
debug = True
skip_mta = False
email_type = html
```

I see nothing in the logs to indicate any issues. As I can change AUTH_REQUIRED = False and I'm able to create users and APIs, it suggests that the other settings are correct. I've been deleting the postgresql_data volume in between changing settings to ensure that I spin up a new DB each time I test.

Thanks for any help you can offer!
