### ISSUE TITLE
Wrong path when starting behind nginx

### ISSUE THREAD

**Issue by proffust** [alerta/docker-alerta#140]
**Issue Summary**
When starting alerta-web bwhind other nginx missing one / (see screenshot)

**Environment**
- OS: Linux
- API version: 7.2.7
- Deployment: Docker

- Database: MongoDB

- Server config:
  Auth enabled? No
  Customer views? No

- web UI version: 7.2.7
- CLI version: 7.2.7

**To Reproduce**
1. Start alerta-web with docker and custom BASE_URL
```
   alerta-web:
    image: alerta/alerta-web:7.2.7
    depends_on:
      - alerta-db
    environment:
      - DATABASE_URL=mongodb://alerta-db:27017/monitoring
      - AUTH_REQUIRED=False
      - PLUGINS=reject,blackout,normalise,enhance
      - BASE_URL=/alerta/api
    ports:
      - 8080:8080
    networks:
      - frontend
      - alerta-net
    restart: always

  alerta-db:
    image: mongo
    volumes:
      - /var/lib/docker/data/mongodb:/data/db
    networks:
      - alerta-net
    restart: always
```
2. Run second nginx whith location /alerta

```
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - frontend
    volumes:
      - ./nginx_services.conf:/etc/nginx/conf.d/metrics.conf
    restart: always

```
second nginx location conf
```
     location /alerta/ {
        proxy_pass http://alerta-web:8080/alerta/;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

3. Open http://{host}/alerta
4. See logs
```
nginx_1              | 172.16.5.254 - - [24/May/2019:11:04:23 +0000] "GET /alertacss/about.ec2999de.css HTTP/1.1" 404 556 "http://172.30.0.86/alerta/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-"
nginx_1              | 2019/05/24 11:04:23 [error] 8#8: *605 open() "/etc/nginx/html/alertajs/about.19206561.js" failed (2: No such file or directory), client: 172.16.5.254, server: 172.30.0.86, request: "GET /alertajs/about.19206561.js HTTP/1.1", host: "172.30.0.86", referrer: "http://172.30.0.86/alerta/"
nginx_1              | 172.16.5.254 - - [24/May/2019:11:04:23 +0000] "GET /alertajs/about.19206561.js HTTP/1.1" 404 556 "http://172.30.0.86/alerta/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-"
nginx_1              | 2019/05/24 11:04:23 [error] 8#8: *605 open() "/etc/nginx/html/alertajs/app.6912cdcc.js" failed (2: No such file or directory), client: 172.16.5.254, server: 172.30.0.86, request: "GET /alertajs/app.6912cdcc.js HTTP/1.1", host: "172.30.0.86", referrer: "http://172.30.0.86/alerta/"
nginx_1              | 172.16.5.254 - - [24/May/2019:11:04:23 +0000] "GET /alertajs/app.6912cdcc.js HTTP/1.1" 404 556 "http://172.30.0.86/alerta/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" "-"
```

**Expected behavior**
Working alerta-web behind second nginx. In version 6.8 it`s working whith same configuration

**Screenshots**
![image](https://user-images.githubusercontent.com/33157540/58324243-01300e00-7e2f-11e9-95bf-3beb2b4ce5df.png)
