### ISSUE TITLE
Consistent Missing or Invalid config.json file Error

### ISSUE THREAD

**Issue by BenB196** [alerta/docker-alerta#145]
**Issue Summary**
I am trying to setup Alerta in docker, but am consistently getting the error when going to the web ui:
```
ERROR: Failed to connect to Alerta API due to missing or invalid config.json file.

Please confirm a config.json file exists, contains an "endpoint" setting and is in the same directory as the application index.html file.
```

**Environment**
- OS: Linux
- API version: v7.2.7
- Deployment: Docker
- For self-hosted, WSGI environment: N/A

- Database: Postgres

- Server config:
  Auth enabled? No
  Auth provider? N/A
  Customer views? No

- web UI version: v7.2.7
- CLI version: v7.2.7

Here is my setup:

I have a Linux server that has Docker + Docker-compose running on it. The Linux server is in DNS as dockerhost01.domain.com

Docker-compose for Alerta and Postgres:

```
version: '3.7'
services:
  alertadb01:
    image: postgres:latest
    container_name: alertadb01
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: alertaUser
      POSTGRES_PASSWORD: superStrongPassword123
    volumes:
      - /alertadb/data:/var/lib/postgresql/data:rw
    networks:
      - alerta
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
  alerta01:
    depends_on:
      - alertmanager01
      - alertadb01
    image: alerta/alerta-web:latest
    container_name: alerta01
    volumes:
      - /alertadb/conf/alertad.conf:/app/alertad.conf
      - /alertadb/conf/alertad.conf:/app/alerta.conf
      - /alertadb/conf/config.json:/web/config.json
    environment:
      - DATABASE_URL=postgres://alertaUser:superStrongPassword123@alertadb01:5432/monitoring
    ports:
      - "8082:8080"
    networks:
      - alerta
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
networks:
  alerta:
    driver: bridge
```

alertad.conf

```
DEBUG = True
SECRET = "^Bpa%i8_nCAc8fI4l9)nhn2EG2!@Gdwad"
AUTH_REQUIRED = False

SEVERITY_MAP = {
    'fatal': 0,
    'critical': 1,
    'major': 2,
    'minor': 3,
    'warning': 4,
    'indeterminate': 5,
    'cleared': 5,
    'normal': 5,
    'ok': 5,
    'informational': 6,
    'debug': 7,
    'trace': 8,
    'unknown': 9
}
DEFAULT_NORMAL_SEVERITY = 'normal', 'ok', 'cleared'
DEFAULT_PREVIOUS_SEVERITY = 'indeterminate'

PLUGINS = ['reject', 'blackout', 'prometheus', 'normalise']
```

alerta.conf

```
[DEFAULT]
sslverify = no
output = psql
endpoint = http://dockerhost01.domain.com:8082/api
timezone = America/New_York
```

config.json

```
{"endpoint": "http://dockerhost01.domain.com:8082/api"}
```

Alerta runs fine, however when I go to the web ui at: http://dockerhost01.domain.com:8082 I get the error mentioned above.

I have tried many different configurations and looked through the docs, but I must be missing something. Any help would be appreciated in getting this to work as Alerta seems like a really cool and useful tool.
