### ISSUE TITLE
alerta-web container grows to fill host disk

### ISSUE THREAD

**Issue by mdfischer** [alerta/docker-alerta#169]
**Issue Summary**
I have deployed alerta-web on an AWS EC2 instance with 8GB of storage along with Postgres using the docker-compose setup suggested in the docs, with very little modification, as such: 
```
version: '3.1'
services:
  web:
    build: .
    image: alerta/alerta-web
    depends_on:
      - db
    volumes:
      - /home/ubuntu/alerta/logs:/var/log/
      - /home/ubuntu/alerta/alertad.conf:/app/alertad.conf
      - /home/ubuntu/alerta/config.json:/web/config.json
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - SECRET_KEY=$ALERTA_SECRET_KEY
      - ADMIN_PASSWORD=alerta
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin
      - PLUGINS=slack
    restart: always
  db:
    image: postgres
    volumes:
      - /home/ubuntu/alerta/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
``` 
After about 2 weeks running, the service became unresponsive and I found that the disk was completely full.  I managed to tear it all down and restart, this time with 16GB of storage, and have watched the container steadily growing again.  I have about a week left until it runs out of space and I'm back in the same situation.

Everything I have read about managing Docker host disk usage has been unhelpful.  Docker system prune (also with -a option) does nothing.  Here's a snapshot of my situation:
```
docker container ls
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
4fc5c9d6941e        alerta/alerta-web   "docker-entrypoint.s…"   10 days ago         Up 7 days           0.0.0.0:80->8080/tcp   alerta_web_1
4c845b58fe64        postgres            "docker-entrypoint.s…"   10 days ago         Up 7 days           5432/tcp               alerta_db_1
```
```
docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              2                   2                   1.723GB             0B (0%)
Containers          2                   2                   1.19GB              0B (0%)
Local Volumes       1                   0                   0B                  0B
Build Cache         0                   0                   0B                  0B
```
```
docker volume ls
DRIVER              VOLUME NAME
local               b4566d6a2059dc2f7b5219e436b1918aed3acec1578388b41391aba403b2ad58
```
```
docker system prune -a
WARNING! This will remove:
        - all stopped containers
        - all networks not used by at least one container
        - all images without at least one container associated to them
        - all build cache
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
```
0B reclaimed.  Re-running the above commands gives the exact same picture.
I ran a CRON job with `du` over the past week to track the growth of files on the host system and these two are the main offenders, the alerta-web container (ID starts with `4fc5`) and whatever is in `overlay2/*/diff/tmp`:
`/var/snap/docker/common/var-lib-docker/containers/4fc5c9d6941eeb1c0bcf7ae135fe7b8b80d50a3c3f65f0989872d729d5e3d44b`  
growing from 444MB to 2277MB
and
`/var/snap/docker/common/var-lib-docker/overlay2/6d2eebce5bbc32f2074ec30b3257cd8d4b7216ed10204208c10564868d2f2757/diff/tmp` 
growing from 380MB to 1117MB

Also, the Alerta logs are not the culprit:
```
~/alerta/logs$ ls -lh
total 5.4M
-rw-r--r-- 1 1001 root  49K Mar 20 20:59 alertad.log
-rw-r--r-- 1 1001 root 1.7M Mar 20 20:58 alertad.log.1
-rw-r--r-- 1 1001 root 3.7M Mar 20 20:59 alertad.log.2
```

**Environment**
- OS: Ubuntu Linux 18.04
- API version: 7.4.4
- Deployment: Docker, docker-compose
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? password login
  Customer views? No

- web UI version: 7.4.4
- CLI version: 7.4.4

**To Reproduce**
1. install python3-dev, python3-pip, docker.io on host
2. create alerta directory in ~ and put `alertad.conf`, `config.json`, and `docker-compose.yaml` in there
3. run `docker-compose up`
4. wait...

**Comment by satterly** [comment]
What is `/var/snap`? Are you taking regular snapshots of docker?

**Comment by mdfischer** [comment]
`/var/snap` is where packages installed by Ubuntu's Snap package manager store their temporary stuff.  I installed Docker using snap: `sudo snap install Docker`

**Comment by satterly** [comment]
What happens if you don't use `snap`?

**Comment by mdfischer** [comment]
I had that thought today too.  Will give it a try...

**Comment by mdfischer** [comment]
OK, so I found the problem.  It was not related to whether Docker was installed via snap or apt (which exhibited the same behaviour when I tried it that way).

I had Alerta's logging set to `DEBUG=True`, which understandably creates lots of output.  I didn't think this was a problem though because I was writing the logs to a host volume (as shown in `docker-compose.yaml`) and it was implementing a 3-file rolling log buffer.  BUT, I was unaware that Docker by default was also grabbing this output and writing it to its log file at location
`/var/lib/docker/containers/<CONTAINER ID>/<CONTAINER ID>-json.log`
with no such rollover.  This is the default configuration for Docker (which I think is silly), and can be changed by adding a rolling buffer config for the container to `docker-compose.yaml`:
```
logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
```

Thanks for your quick response in any case!  Keep well.
