### ISSUE TITLE
remove cron from container

### ISSUE THREAD

**Issue by freeseacher** [alerta/docker-alerta#24]
Cron is proved to be buggy in docker and can be removed from container with that simple hack in docker-compose.yaml 
```
  alerta_cron_heartbeats:
    image: alerta/alerta-web:latest
    restart: always
    depends_on:
      - alerta-db
    volumes:
      - ./alerta/heartbeat.sh:/heartbeat.sh
    command: /heartbeat.sh
```

and
```
# cat ./alerta/heartbeat.sh
#!/bin/sh
sleep 60
alerta heartbeats --alert

```
it keeps all the things simplier.
container will be restarted by docker and looks like it is cron
