### ISSUE TITLE
Storing the configuration in volumes

### ISSUE THREAD

**Issue by Scott-Phosphore** [alerta/docker-alerta#30]
Hi,

I'm running Alerta in a docker container on DC/OS platform. Everytime I restart Alerta, it creates a new container, so I have to save the configuration in volumes to keep it across reboots. Currently, the API keys generated via the WebUI are lost. Can you tell me which files I need to put in volumes to make the configuration persistent ?

**Comment by satterly** [comment]
All persistent data is kept in the mongo database so you'll need to ensure that is stored in a volume like this ...
```
version: '2.1'
services:
  alerta-web:
    image: alerta/alerta-web
    ports:
      - "8181:80"
    depends_on:
      - alerta-db
    environment:
      - MONGO_URI=mongodb://alerta-db:27017/monitoring
    restart: always
  alerta-db:
    image: mongo
    volumes:
      - ./mongodb:/data/db
    restart: always
```
See the README for full examples.
