### ISSUE TITLE
GET http://ip:port/api/user/me/attributes 404 (NOT FOUND)

### ISSUE THREAD

**Issue by zhangrj** [alerta/docker-alerta#362]
I'm install alerta in k8s use the following yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerta
  namespace: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alerta    
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alerta
        app.kubernetes.io/version: 8.7.0
    spec:
      containers:
      - image: alerta/alerta-web:8.7.0
        name: alerta
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ADMIN_PASSWORD
          value: alerta
        - name: ADMIN_USERS
          value: admin
        volumeMounts:
        - name: config-volume
          mountPath: /app/alertad.conf
          subPath: alertad.conf
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: config-volume
        configMap:
          name: alerta-config
```

```
apiVersion: v1
data:
  alertad.conf: |-
    DATABASE_URL = 'postgres://10.12.52.5:5432/alerta?user=app&password=alerta99'
    PLUGINS = ['prometheus']
    SEVERITY_MAP = {
        'Emergency': 1,
        'Critical': 2,
        'Warning': 3,
        'Info': 4,
        'major': 9
    }
    DEFAULT_NORMAL_SEVERITY = 'Info'
    DEFAULT_PREVIOUS_SEVERITY = 'Warning'

    COLOR_MAP = {
        'severity': {
            'Emergency': 'red',
            'Critical': 'orange',
            'Warning': 'lightblue',
            'Info': 'white',
            'major': 'silver'
        },
        'text': 'black'
    }
    ALERT_TIMEOUT = 0
    DELETE_EXPIRED_AFTER = 0
    DELETE_INFO_AFTER = 0
kind: ConfigMap
metadata:
  name: alerta-config
  namespace: alertmanager
```
```
apiVersion: v1
kind: Service
metadata:
  name: alerta
  namespace: alertmanager
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: http
    nodePort: 31003
  selector:
    app.kubernetes.io/name: alerta
```

Everything working fine, but an error occur on the web UI, " 404 not Found"，the URL is:
```http://10.12.52.6:31003/api/user/me/attributes```

![](https://s3.bmp.ovh/imgs/2021/12/6b15fdc92a236403.png)

Anyone can help me?  Thanks!
