### ISSUE TITLE
ORDER BY (false)

### ISSUE THREAD

**Issue by Pierre-LBou** [alerta/docker-alerta#412]
**Environment**
- OS: Windows
- API version: 6.8.5
- Deployment: Docke

- Database:  Postgres

- Server config:
  Auth enabled? No

- web UI version: 7.0

**Expected behavior**
On the tabs "Users", "groups", "downtime management", "permissions", "api keys" I have the following error:
![image](https://user-images.githubusercontent.com/114667166/196963286-39cd69b8-8e32-4b0e-bbff-03c286223ad8.png)
This error prevents me from using all the features correctly.

Sending alerts and displaying alerts works properly without any bugs.

**Screenshots**
![image](https://user-images.githubusercontent.com/114667166/197154256-624a0b42-1c00-4c9a-ab54-afdb6be1a24d.png)

![image](https://user-images.githubusercontent.com/114667166/197137723-75016a9d-22ef-4633-a743-485df7c5ca45.png)

Config docker file
```yml
version: '3.1'

services:
  web:
    image: alerta/alerta-web
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - PLUGINS=reject,blackout,normalise,enhance
    restart: always
  db:
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
```
