### ISSUE TITLE
Can't use AUTH_REQUIRED=True with Prometheus Alertmanager

### ISSUE THREAD

**Issue by qed-** [alerta/docker-alerta#6]
With AUTH_REQUIRED=True set on the docker command line Alertmanager is unable to send alerts to Alerta (fails with HTTP 401 error code)

**Comment by satterly** [comment]
You need to create an API key and then add it to the alertmanager configuration so the config will look something like ...
```
receivers:
- name: "alerta"
  webhook_configs:
  - url: 'http://localhost:8080/webhooks/prometheus?api-key=foo'
    send_resolved: true
```
