### ISSUE TITLE
Environment variables for GITLAB_URL is not used in docker-entrypoint.sh

### ISSUE THREAD

**Issue by onedr0p** [alerta/docker-alerta#86]
Hi,

I am trying to set up Gitlab auth and noticed that GITLAB_URL is not present in here.

I would expect the config to be something like this:
```js
'use strict';
angular.module('config', [])
  .constant('config', {
    'endpoint'    : "${BASE_URL}",
    'provider'    : "${PROVIDER}",
    'gitlab_url'   : "${GITLAB_URL}"
    'client_id'   : "${OAUTH2_CLIENT_ID}",
    'colors'      : {}
  });
```

There seems to be a huge difference and some options are available in the kubernetes frontend config.
https://github.com/alerta/docker-alerta/blob/master/contrib/kubernetes/frontend/config.js.template

Are there any plans to support all these settings in the standard `docker-entrypoint.sh`

**Comment by satterly** [comment]
If you create a file that you make available using volumes to Docker and map it to `/web/config.js` then it will be used. That way it is not necessary to make all the setting available as environment variables, like the kubernetes example (which I didn't write, btw).

Here is an example docker compose file that uses local versions of Alerta server, client and web UI config files then maps them to the filenames expected by the Docker container.

```yaml
version: '3.1'
services:
  web:
    image: alerta/alerta-web
    volumes:
      - $PWD/config/alertad.conf.example:/app/alertad.conf
      - $PWD/config/alerta.conf.example:/app/alerta.conf
      - $PWD/config/config.js.example:/web/config.js
    ports:
      ...
```

FYI, all the magic happens [here](https://github.com/alerta/docker-alerta/blob/master/docker-entrypoint.sh#L7) where the `docker-entrypoint.sh` script checks to see if a web config file is supplied and if not creates a basic one.

Let me know if you need more info.
